### ISSUE TITLE
gh action: Adding issues to org project failing

### ISSUE THREAD

**Issue by Samir-Rashid** [tritonuas/obcpp#135]
## 🐛 Bug

All the actions to add issues to the organization project are failing.
See: https://github.com/tritonuas/obcpp/actions/runs/8547621172/job/23420090814#step:2:5

As I understand, it is because this token has been invalidated or expired somehow 
https://github.com/tritonuas/obcpp/blob/69bd408d870d059037f529f0c643f96f6445bc86/.github/workflows/github-project-issue.yml#L18

## Potential Fix

Update the token?
https://github.com/organizations/tritonuas/settings/secrets/actions/ADD_TO_PROJECT_PAT

## To reproduce

Watch the action fail on this issue... ([there ya go, as expected](https://github.com/tritonuas/obcpp/actions/runs/8549044155))

**Comment by atar13** [comment]
yeah this explains why the docker push failed on the gcs as well. I will update $soon^{tm}$

**Comment by atar13** [comment]
Resolved by making secrets accessible to all repositories (not just private ones).
