### ISSUE TITLE
Allow GCS to activate manual takeoff or autonomous takeoff

### ISSUE THREAD

**Issue by Tyler-Lentz** [tritonuas/obcpp#178]
Currently, we go straight from path validate to mav upload to takeoff. 

## Description

What we want is:

1. GCS: Click on Path Validate
2. OBC: PathValidate -> MavUpload -> WaitForTakeoff
3. GCS: Somewhere on control page, have an option to either manual takeoff of auto takeoff
4. OBC: Receives this msg, and then transitions to manual/auto takeoff

### GCS

1. Option in the mission control page to specify an auto or manual takeoff

### Protos

2. https://github.com/tritonuas/protos
3. Create new message type for specifying auto/manual takeoff

### OBC

4. Create new event handler for a route to handle transition from WaitForTakeoff to one of the takeoff options
5. Once you get this far either double check back here and ill have written more specific instructions, or just ask me for help
6. Can look at the gcs handler for path validate for inspiration
    - https://github.com/tritonuas/obcpp/blob/main/src/network/gcs_routes.cpp
    - https://github.com/tritonuas/obcpp/blob/main/src/ticks/path_validate.cpp

**Comment by MatthewHsu1** [comment]
lgtm
