### ISSUE TITLE
Config JSON

### ISSUE THREAD

**Issue by Tyler-Lentz** [tritonuas/obcpp#74]
We need a `config.json` file which lives in the repo to keep track of parameters with which to run the OBC. Something in the code should load in the config file, then save the values somehow to be loaded into the rest of the program where needed. If the config file doesn't exist, a default one should be generated. In addition, we should be able to specify what config file to use on the command line by passing a command line argument, so that we can have separate config files for production (`config.json`) and development (`dev-config.json`). This is what the development config file should have as defaults:

```json
{
    "network": {
        "mavlink": {
            "connect": "tcp://172.17.0.1:5760",
        },
        "gcs": {
            "port": 5010,
        },
    }
}
```

And this is what the production `config.json` should look like:

```json
{
    "network": {
        "mavlink": {
            "connect": "serial:///dev/ttyACM0",
        },
        "gcs": {
            "port": 5010,
        },
    }
}
```

Step 1: try to load a config file based on the first command line argument

e.g. ./obcpp dev-config.json

Step 2: take the values from the config files, and load them into the appropriate parts of the OBC

 - GCS Port
 - Mavlink connection URL

Note: we are using this json library https://github.com/nlohmann/json

**Comment by atar13** [comment]
File paths to the model files:

- saliency model path
- matching model path
- segmentation model path
- color classification model path
- shape classification model path
- character classification model path

**Comment by atar13** [comment]
Also some options for customizing the CV pipeline;

- localizationType: either "ECEF" or "GSD"
- pipelineType: either "Matching" or "Classification"

**Comment by atar13** [comment]
These also (except for the first one): 

https://discord.com/channels/772996212000948244/997656326199070760/1220175561398157423

**Comment by AskewParity** [comment]
Static Pathing:
- booleans:
  - optimize
- doubles/floats:
  - rewireRadius
  - pointSeperation
- integers:
  - iterationsPerWaypoint
- enumerations:
  - pointFetchMethod: "NONE", "RANDOM", "CLOSEST"
